"""empty message

Revision ID: 43b55eb5dec4
Revises: 11d784c8e907
Create Date: 2024-08-02 11:51:10.663784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43b55eb5dec4'
down_revision: Union[str, None] = '11d784c8e907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TEST_TABLE',
    sa.Column('SECID', sa.String(), nullable=False)
    )
    op.create_table('correlations',
    sa.Column('SECID', sa.String(), nullable=False),
    sa.Column('FXSECID', sa.String(), nullable=False),
    sa.Column('TRADEDATE', sa.TIMESTAMP(), nullable=True),
    sa.Column('COEFF_CORRELATION', sa.Float(), nullable=False),
    sa.Column('COEFF_BETA', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('SECID', 'FXSECID')
    )
    op.create_table('quotes',
    sa.Column('SECID', sa.String(), nullable=False),
    sa.Column('begin', sa.TIMESTAMP(), nullable=False),
    sa.Column('end', sa.TIMESTAMP(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('correlations')
    op.drop_table('TEST_TABLE')
    # ### end Alembic commands ###
