"""empty message

Revision ID: 951b5abc95e7
Revises: 43b55eb5dec4
Create Date: 2024-08-02 13:40:59.241484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '951b5abc95e7'
down_revision: Union[str, None] = '43b55eb5dec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TEST_TABLE_NEW',
    sa.Column('SECID', sa.String(), nullable=False)
    )
    op.drop_table('TEST_TABLE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TEST_TABLE',
    sa.Column('SECID', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.drop_table('TEST_TABLE_NEW')
    # ### end Alembic commands ###
