"""Тестовая ревизия

Revision ID: 4cb390435274
Revises: 7d7d11273972
Create Date: 2024-08-13 22:19:52.832644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4cb390435274'
down_revision: Union[str, None] = '7d7d11273972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correlation',
    sa.Column('SECID', sa.String(), nullable=False),
    sa.Column('FXSECID', sa.String(), nullable=False),
    sa.Column('TRADEDATE', sa.TIMESTAMP(), nullable=True),
    sa.Column('COEFF_CORRELATION', sa.Float(), nullable=False),
    sa.Column('COEFF_BETA', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('SECID', 'FXSECID')
    )
    op.create_table('quote',
    sa.Column('SECID', sa.String(), nullable=False),
    sa.Column('begin', sa.TIMESTAMP(), nullable=False),
    sa.Column('end', sa.TIMESTAMP(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True)
    )
    op.drop_table('correlations')
    op.drop_table('quotes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotes',
    sa.Column('SECID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('begin', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('open', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('close', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('high', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('low', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('volume', sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_table('correlations',
    sa.Column('SECID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('FXSECID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('TRADEDATE', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('COEFF_CORRELATION', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('COEFF_BETA', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('SECID', 'FXSECID', name='correlations_pkey')
    )
    op.drop_table('quote')
    op.drop_table('correlation')
    # ### end Alembic commands ###
