"""empty message

Revision ID: 67ee6857bbde
Revises: ab3a77b2d9e4
Create Date: 2024-08-17 11:59:48.956207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67ee6857bbde'
down_revision: Union[str, None] = 'ab3a77b2d9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart',
    sa.Column('SECID', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('SECID', name='chart_pkey')
    )
    # ### end Alembic commands ###
