"""empty message

Revision ID: 7d7d11273972
Revises: 951b5abc95e7
Create Date: 2024-08-03 17:25:21.159337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7d11273972'
down_revision: Union[str, None] = '951b5abc95e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TEST_TABLE_NEW')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('TEST_TABLE_NEW',
    sa.Column('SECID', sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    # ### end Alembic commands ###
