"""empty message

Revision ID: ab3a77b2d9e4
Revises: 4cb390435274
Create Date: 2024-08-13 22:22:00.420036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab3a77b2d9e4'
down_revision: Union[str, None] = '4cb390435274'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart',
    sa.Column('SECID', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('SECID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart')
    # ### end Alembic commands ###
